UruguayBus/Controllers/LineaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Identity;
using Models.Entities;
using Newtonsoft.Json;
using UruguayBus.conexiones;

namespace UruguayBus.Controllers
{
    [Authorize("admin")]
    public class LineaController : Controller
    {
        // GET: LineaController
        string Baseurl = "https://apprestproyectonet.azurewebsites.net/";

        ConexionesController api = new ConexionesController();
        public async Task<ActionResult> ListarLineas()
        {
            List<Linea> ret = new List<Linea>();
            using (var client = new System.Net.Http.HttpClient())
            {
                client.BaseAddress = new Uri(Baseurl);
                client.DefaultRequestHeaders.Accept.Clear();
                // Agrega el header Accept: application/json para recibir la data como json  
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                // Hace la llamada a http://url-base-del-api/api/products/<id>
                var response = await client.GetAsync("api/Linea");

                // Si el servicio responde correctamente
                if (response.IsSuccessStatusCode)
                {
                    var aux = response.Content.ReadAsStringAsync().Result;
                    // Lee el response y lo deserializa como un Product
                    ret = JsonConvert.DeserializeObject<List<Linea>>(aux);
                }
            }
            return View(ret);
        }

        // GET: LineaController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: LineaController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: LineaController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Linea l)
        {
            try
            {
                List<Linea> ret = new List<Linea>();
                using (var client = new System.Net.Http.HttpClient())
                {
                    client.BaseAddress = new Uri(Baseurl);
                    client.DefaultRequestHeaders.Accept.Clear();
                    // Agrega el header Accept: application/json para recibir la data como json  
                    client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                    var json = JsonConvert.SerializeObject(l);
                    var stringContent = new System.Net.Http.StringContent(json, System.Text.UnicodeEncoding.UTF8, "application/json");

                    var response = await client.PostAsync("api/Linea", stringContent);

                    return RedirectToAction("ListarLineas");
                }
            }
            catch
            {
                return RedirectToAction("ListarLineas");
            }
        }
        public async Task<ActionResult> addParada(int id)
        {
            Parada ret = new Parada();
            using (var client = new System.Net.Http.HttpClient())
            {
                client.BaseAddress = new Uri(Baseurl);
                client.DefaultRequestHeaders.Accept.Clear();
                // Agrega el header Accept: application/json para recibir la data como json  
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                // Hace la llamada a http://url-base-del-api/api/products/<id>
                var id2 = id.ToString();
                var response = await client.GetAsync("api/Linea/UltimaParada/" + id2);

                // Si el servicio responde correctamente
                if (response.IsSuccessStatusCode)
                {
                    var aux = response.Content.ReadAsStringAsync().Result;
                    // Lee el response y lo deserializa como un Product
                    ret = JsonConvert.DeserializeObject<Parada>(aux);
                }

                List<Parada> ret2 = new List<Parada>();
                {
                    var response2 = await client.GetAsync("api/Parada");

                    // Si el servicio responde correctamente
                    if (response2.IsSuccessStatusCode)
                    {
                        var aux = response2.Content.ReadAsStringAsync().Result;
                        // Lee el response y lo deserializa como un Product
                        ret2 = JsonConvert.DeserializeObject<List<Parada>>(aux);
                    }
                }
                var cont = 0;
                var au = false;
                if (ret != null)
                {
                    foreach (var item in ret2)
                    {
                        if (item.idParada == ret.idParada)
                        {
                            au = true;
                            break;
                        }
                        cont = cont + 1;
                    }
                    if (au)
                    {
                        ret2.RemoveAt(cont);
                    }
                }
                ViewBag.ParadasList = new SelectList(ret2, "idParada", "nombre");
                ViewBag.idlinea = id;
                ViewBag.paradaAnterior = ret;
                return View();
            }
        }

        public async Task<ActionResult> VerParadas(int id)
        {
            List<Parada> ret = new List<Parada>();
            using (var client = new System.Net.Http.HttpClient())
            {
                client.BaseAddress = new Uri(Baseurl);
                client.DefaultRequestHeaders.Accept.Clear();
                // Agrega el header Accept: application/json para recibir la data como json  
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                // Hace la llamada a http://url-base-del-api/api/products/<id>
                var id2 = id.ToString();
                var response = await client.GetAsync("api/Linea/Paradas/"+ id2);

                if (response.IsSuccessStatusCode)
                {
                    // Si el servicio responde correctamente
                    var aux = response.Content.ReadAsStringAsync().Result;
                    // Lee el response y lo deserializa como un Product
                    ret = JsonConvert.DeserializeObject<List<Parada>>(aux);

                }
                var response2 = await client.GetAsync("api/Linea/" + id2);
                if (response2.IsSuccessStatusCode)
                {
                    // Si el servicio responde correctamente
                    var aux2 = response2.Content.ReadAsStringAsync().Result;
                    // Lee el response y lo deserializa como un Product
                    Linea ret2 = JsonConvert.DeserializeObject<Linea>(aux2);
                    ViewBag.paradaAnterior = ret2.ParadaAnterior;
                }
                ViewBag.paradas = ret;
                ViewBag.idLinea = id;
                return View(ret);
            }
        }

        public ActionResult VerPrecios(int id)
        {
                var ret = api.getPrecios(id);
                List<Precios> re2 = ret.Result;
                ViewBag.idParadaAnteriror = id;
                re2.Reverse();
                return View(re2);
            
        }

        public ActionResult addPrecios(int id)
        {
            ViewBag.idParadaAnteriror = id;
            return View();
        }

        public ActionResult addPrecios2(int idparadaAnterior,int precio, DateTime FechaCaducidad)
        {
            var ret = new DtoPrecio();
            ret.idparadaAnterior = idparadaAnterior;
            ret.precio = precio;
            ret.FechaCaducidad = FechaCaducidad;
            api.addPrecio(ret);
            var id2 = idparadaAnterior.ToString();
            return RedirectToAction("VerPrecios/" + id2);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> addParada2(string Tiempo, int Precio, string FechaDeCaducidad, int ParadaSiguiente, int idlinea)
        {
            try
            {
                List<Linea> ret = new List<Linea>();
                using (var client = new System.Net.Http.HttpClient())
                {
                    client.BaseAddress = new Uri(Baseurl);
                    client.DefaultRequestHeaders.Accept.Clear();
                    // Agrega el header Accept: application/json para recibir la data como json  
                    client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                    DTOaddParada dto = new DTOaddParada();
                    dto.idlinea = idlinea;
                    dto.idParada = ParadaSiguiente;
                    dto.tiempo = Tiempo;
                    dto.precio = Precio;
                    if(FechaDeCaducidad == null)
                    {
                        dto.fechacaducidad = "2026-10-23T10:16:40";
                        dto.tiempo = "2026-10-23T00:00:00";
                        dto.precio = 0;
                    }
                    else
                    {
                        dto.fechacaducidad = FechaDeCaducidad;
                    }
                    

                    var json = JsonConvert.SerializeObject(dto);
                    var stringContent = new System.Net.Http.StringContent(json, System.Text.UnicodeEncoding.UTF8, "application/json");

                    var response = await client.PostAsync("api/Linea/AddParada", stringContent);
                    var id2 = idlinea.ToString();

UruguayBus/Controllers/ViajeController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Models.Entities;
using Models.Enums;
using UruguayBus.conexiones;
using UruguayBus.Data;

namespace UruguayBus.Controllers
{
    [Authorize("admin")]
    public class ViajeController : Controller
    {
        ConexionesController api = new ConexionesController();
        [BindProperty]
        public List<Dia> Selected { get; set; }
        // GET: ViajeController
        public ActionResult ListarViajes()
        {
            var ret = api.getViajes().Result;
            return View(ret);
        }

        // GET: ViajeController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ViajeController/Create
        public ActionResult Create()
        {
            var h = api.getHorarios().Result;
            var aux3 = new List<Horario>();

            foreach (Horario element in h)
            {
                if(!element.Viaje)
                {
                    aux3.Add(element);
                }

            }


            var d = new List<Dia>();
            var d1 = new Dia();

            d1.idDia = 1;
            d1.nombre = "Lunes";
            d.Add(d1);

            var d2 = new Dia();
            d2.idDia = 2;
            d2.nombre = "Martes";
            d.Add(d2);

            var d3 = new Dia();
            d3.idDia = 3;
            d3.nombre = "Miercoles";
            d.Add(d3);

            var d4 = new Dia();
            d4.idDia = 4;
            d4.nombre = "Jueves";
            d.Add(d4);

            var d5 = new Dia();
            d5.idDia = 5;
            d5.nombre = "Viernes";
            d.Add(d5);

            var d6 = new Dia();
            d6.idDia = 6;
            d6.nombre = "Sabado";
            d.Add(d6);

            var d7 = new Dia();
            d7.idDia = 7;
            d7.nombre = "Domingo";
            d.Add(d6);

            ViewBag.HorariosList = new SelectList(aux3, "idHorario", "FullName");
            ViewBag.DiasList = new MultiSelectList(d, "idDia", "nombre");
            return View();
        }

        Temp T = Temp.Instance;
        [HttpPost]
        public void updateSelec([FromBody]string v)
        {
            var d = new List<Dia>();
            if(T.Selected != null)
            Selected = T.Selected;

            var d1 = new Dia();
            d1.idDia = 1;
            d1.nombre = "Lunes";
            d.Add(d1);

            var d2 = new Dia();
            d2.idDia = 2;
            d2.nombre = "Martes";
            d.Add(d2);

            var d3 = new Dia();
            d3.idDia = 3;
            d3.nombre = "Miercoles";
            d.Add(d3);

            var d4 = new Dia();
            d4.idDia = 4;
            d4.nombre = "Jueves";
            d.Add(d4);

            var d5 = new Dia();
            d5.idDia = 5;
            d5.nombre = "Viernes";
            d.Add(d5);

            var d6 = new Dia();
            d6.idDia = 6;
            d6.nombre = "Sabado";
            d.Add(d6);

            var d7 = new Dia();
            d7.idDia = 7;
            d7.nombre = "Domingo";
            d.Add(d6);

            int aux = 0;
            bool a = true;
            foreach (Dia element in Selected)
            {
                if (element.nombre == v)
                {
                    a = false;
                }
                else
                    aux = aux + 1;
            }
            if (!a)
            {
               T.Selected.RemoveAt(aux);
            }
            if (T.Selected != null)
                Selected = T.Selected;
            if (a)
            {
                foreach (Dia element2 in d)
                   if (v == element2.nombre)
                   {
                        Selected.Add(element2);
                        T.Selected = Selected;
                   }
            }
             

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(DateTime fechaInicial, DateTime fechaFinal, int idHorario)
        {

            if (idHorario == 0)
            {
                ModelState.AddModelError("horario", "Debe seleccionar un horario");
            }

            var dto = new DtoViaje();
            dto.fechaInicial = fechaInicial;
            dto.fechaFinal = fechaFinal;
            dto.DiasViaje = T.Selected;
            dto.idHorario = idHorario;
            if (idHorario != 0 && T.Selected.Count != 0)
            {
                api.addViaje(dto);
                return RedirectToAction("ListarViajes");
            }
            else return RedirectToAction("Create");
        }

        // GET: ViajeController/Edit/5
        public ActionResult Edit(int id)
        {
            var v = api.getViaje(id).Result;
            var h = api.getHorarios().Result;
            ViewBag.VehiculoList = new SelectList(h, "idHorario", "FullName", v.Horario.idHorario);
            return View(v);
        }

        // POST: ViajeController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Viaje v)
        {
            api.UpdateViaje(v);
            System.Threading.Thread.Sleep(1000);
            return RedirectToAction("ListarViajes");
        }

        // GET: ViajeController/Delete/5
        public ActionResult Delete(int id)
        {
            var v = api.getViaje(id).Result;
            ViewBag.id = id;
            return View(v);
        }

        // POST: ViajeController/Delete/5

        public ActionResult Delete2(int id)
        {
            api.DeleteViaje(id);
            System.Threading.Thread.Sleep(1000);
            return RedirectToAction("ListarViajes");
        }
    }
}

UruguayBus/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using UruguayBus.Areas.Identity.Data

@inject SignInManager<UruguayBusUser> SignInManager
@inject UserManager<UruguayBusUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UruguayBus</title>
    <link rel="shortcut icon" type="image/png" href="https://play-lh.googleusercontent.com/dvgm8fcUEsh96OtJ1G1EMQ8YMwp5FTsSPCyiIvGt3bHPRdCUk9lSnLQfk9Dw2b4p_Q"/>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://kit.fontawesome.com/d2e9cc5742.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
          integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
          crossorigin="" />
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
</head>
<body id="page-top">
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav" style="background: ghostwhite;">
        <a class="navbar-brand js-scroll-trigger" style="color: midnightblue;" asp-area="" asp-controller="Home" asp-action="Index">Uruguay Bus</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">

            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item active">
                    <a class="nav-link" style="color:black" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                </li>

                @if (SignInManager.IsSignedIn(User))
                {
                @if(UruguayBus.Data.Temp.Instance.GetUs().rol == "Conductor"){
                <li class="nav-item">
                    <a class="nav-link" style="color:black" href="@Url.Action("ComienzoDeViaje", "Control")">
                        Comienzo del Viaje
                    </a>
                </li>
                }
                @if(UruguayBus.Data.Temp.Instance.GetUs().rol == "superadmin"){
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" style="color:black" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Control
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" style="color:black" href="@Url.Action("AsignarRoles", "Control")">
                            Asignacion de Roles
                        </a>

                        <a class="dropdown-item" style="color:black" href="@Url.Action("PanelDeControlVehiculos", "Control")">
                            Panel de Control de Vehiculos
                        </a>


                    </div>
                </li>


                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" style="color:black" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Reportes
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" style="color:black" href="@Url.Action("PasajesVendidos", "Reporte")">
                            Ventas de Pasajes
                        </a>

                        <a class="dropdown-item" style="color:black" href="@Url.Action("EstadisticasViajes", "Reporte")">
                            Estadisticas de Viajes
                        </a>



                    </div>
                </li>
                }
                @if(UruguayBus.Data.Temp.Instance.GetUs().rol == "superadmin" || UruguayBus.Data.Temp.Instance.GetUs().rol == "admin"){
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" style="color:black" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Gestion de
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" style="color:black" href="@Url.Action("ListarVehiculos", "Vehiculo")">
                            Vehiculos
                        </a>

                        <a class="dropdown-item" style="color:black" href="@Url.Action("ListarViajes", "Viaje")">
                            Viajes
                        </a>


                        <a class="dropdown-item" style="color:black" href="@Url.Action("ListarHorarios", "Horarios")">
                            Horarios
                        </a>

                        <a class="dropdown-item" style="color:black" href="@Url.Action("ListarLineas", "Linea")">
                            Lineas
                        </a>

                        <a class="dropdown-item" style="color:black" href="@Url.Action("ListarParadas", "Paradas")">
                            Paradas
                        </a>

                        <a class="dropdown-item" style="color:black" href="@Url.Action("ListarConductores", "Conductores")">
                            Conductores
                        </a>

                    </div>
                </li>
                }
                }
            </ul>
            <partial name="_LoginPartial" />
        </div>
    </nav>
    <div class="contenido">
        <main role="main">

            <header class="masthead" style="height:1600px">

                @RenderBody()


            </header>

            <!-- Bootstrap core JS-->
            <div class="footer bg-light small text-center text-black-50" style="display:flex;justify-content:center;">
                <div class="container" style="text-align:center;color:black">
                    &copy; 2020 - UruguayBus - UTEC - ProyectoNET
                </div>
            </div>
        </main>
    </div>



    @section scripts {

        <script>

            $(document).ready(function () {
                $("button").tooltip();
            });

        </script>

    }

    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
            integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
            crossorigin=""></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>